const images = {
    IMG_0: require('../images/IMG_0.jpg'),
    IMG_1: require('../images/IMG_1.jpg'),
    IMG_2: require('../images/IMG_2.jpg'),
    IMG_3: require('../images/IMG_3.jpg'),
    IMG_4: require('../images/IMG_4.jpg'),
    IMG_5: require('../images/IMG_5.jpg'),
    IMG_6: require('../images/IMG_6.jpg'),
    IMG_7: require('../images/IMG_7.jpg'),
    IMG_8: require('../images/IMG_8.jpg'),
    IMG_9: require('../images/IMG_9.jpg'),
    IMG_10: require('../images/IMG_10.jpg'),
    IMG_11: require('../images/IMG_11.jpg'),
    IMG_12: require('../images/IMG_12.jpg'),
    IMG_13: require('../images/IMG_13.jpg'),
    IMG_14: require('../images/IMG_14.jpg'),
    IMG_15: require('../images/IMG_15.jpg'),
    IMG_16: require('../images/IMG_16.jpg'),
    IMG_17: require('../images/IMG_17.jpg'),
    IMG_18: require('../images/IMG_18.jpg'),
    IMG_19: require('../images/IMG_19.jpg'),
    IMG_20: require('../images/IMG_20.jpg'),
    IMG_21: require('../images/IMG_21.jpg'),
    IMG_22: require('../images/IMG_22.jpg'),
    IMG_23: require('../images/IMG_23.jpg'),
    IMG_24: require('../images/IMG_24.jpg'),
    IMG_25: require('../images/IMG_25.jpg'),
    IMG_26: require('../images/IMG_26.jpg'),
    IMG_27: require('../images/IMG_27.jpg'),
    IMG_28: require('../images/IMG_28.jpg'),
};

export default images;
